memo/app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:memo_id>', views.detail, name='detail'),
    path('new_memo', views.new_memo, name='new_memo'),
]

memo/memo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

memo/app/models.py
from django.db import models

# Create your models here.

class Memo(models.Model):
    title = models.CharField(max_length=150)
    text = models.TextField(blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

memo/app/views.py
from django.shortcuts import render
from .models import Memo
from django.shortcuts import get_object_or_404

def index(request):
  memos = Memo.objects.all().order_by('-updated_datetime')
  return render(request, 'app/index.html', { 'memos': memos })

def detail(request, memo_id):
  memo = get_object_or_404(Memo, id=memo_id)
  return render(request, 'app/detail.html', {'memo': memo})

def new_memo(request):
  return render(request, 'app/new_memo.html')

memo/app/templates/app/detail.html
<div>
    <a href="{% url 'app:index' %}">ホームに戻る</a>
</div>

<h2>{{ memo.title }}</h2>
<div>
    {{ memo.text | linebreaks | urlize }}
</div>

memo/app/templates/app/index.html
<a class="btn" href="{% url 'app:new_memo' %}">新規メモ作成</a>

{% for memo in memos %}
<a href="{% url 'app:detail' memo.id %}" class="memo-title">
    <div>
        {{ memo }}
        <span class="updated_datetime">{{ memo.updated_datetime }}</span>
    </div>
</a>
{% endfor %}

memo/app/templates/app/new_memo.html
<div>
    <a href="{% url 'app:index' %}">ホームに戻る</a>
</div>